<?php

namespace App\Http\Requests\Api;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Http\Exceptions\HttpResponseException;

abstract class ApiFormRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    /**
     * @return array<string, string>
     */
    public function messages(): array
    {
        return [
            'action.max' => 'The action filter may not be greater than :max characters.',
            'actor_role.max' => 'The actor role filter may not be greater than :max characters.',
            'address.max' => 'The service address may not be greater than :max characters.',
            'admin_note.max' => 'The admin note may not be greater than :max characters.',
            'approval_status.in' => 'Please choose a valid approval status.',
            'available_date.date_format' => 'The available date must be in YYYY-MM-DD format.',
            'available_time.date_format' => 'The available time must be in HH:MM format.',
            'bio.max' => 'The bio may not be greater than :max characters.',
            'booking_date.after_or_equal' => 'The booking date must be today or a future date.',
            'booking_date.date_format' => 'The booking date must be in YYYY-MM-DD format.',
            'booking_date.required' => 'Please choose a booking date.',
            'booking_id.exists' => 'The selected booking is invalid.',
            'booking_id.integer' => 'The selected booking is invalid.',
            'booking_id.required' => 'Please choose a booking.',
            'worker_request_id.exists' => 'The selected worker request is invalid.',
            'worker_request_id.integer' => 'The selected worker request is invalid.',
            'worker_request_id.required' => 'Please choose a worker request.',
            'cancelled_reason.max' => 'The cancellation reason may not be greater than :max characters.',
            'category.in' => 'Please choose a valid dispute category.',
            'category.max' => 'The category may not be greater than :max characters.',
            'category.required' => 'Please choose a category.',
            'certificates.array' => 'The certificates must be uploaded as a list.',
            'certificates.max' => 'You may upload up to :max certificates.',
            'certificates.*.mimes' => 'Each certificate must be a JPG, JPEG, PNG, or PDF file.',
            'certificates.*.max' => 'Each certificate may not be greater than :max kilobytes.',
            'city.max' => 'The city may not be greater than :max characters.',
            'city.required' => 'Please provide city.',
            'commission_rate.max' => 'The commission rate may not be greater than 100%.',
            'commission_rate.min' => 'The commission rate cannot be negative.',
            'commission_rate.numeric' => 'The commission rate must be a number.',
            'commission_rate.required' => 'Please provide commission rate.',
            'date.date_format' => 'The date must be in YYYY-MM-DD format.',
            'date.required' => 'Please choose a date.',
            'date_from.date_format' => 'The start date must be in YYYY-MM-DD format.',
            'date_to.after_or_equal' => 'The end date must be on or after the start date.',
            'date_to.date_format' => 'The end date must be in YYYY-MM-DD format.',
            'day_of_week.between' => 'Please choose a day between 0 and 6.',
            'day_of_week.integer' => 'The day of week must be a whole number.',
            'day_of_week.required' => 'Please choose a day of week.',
            'description.max' => 'The description may not be greater than :max characters.',
            'description.min' => 'The description must be at least :min characters.',
            'description.required' => 'Please provide description.',
            'duration_minutes.max' => 'The booking duration may not be greater than :max minutes.',
            'duration_minutes.min' => 'The booking duration must be at least :min minutes.',
            'duration_minutes.required' => 'Please provide booking duration.',
            'email.email' => 'Please enter a valid email address.',
            'email.lowercase' => 'The email address must be lowercase.',
            'email.max' => 'The email address may not be greater than :max characters.',
            'email.required' => 'Please provide email address.',
            'email.unique' => 'This email address is already registered.',
            'end_time.after' => 'The end time must be after the start time.',
            'end_time.date_format' => 'The end time must be in HH:MM format.',
            'end_time.required_unless' => 'Please provide an end time unless this is marked as an off day.',
            'experience_years.integer' => 'The years of experience must be a whole number.',
            'experience_years.max' => 'The years of experience may not be greater than :max.',
            'experience_years.min' => 'The years of experience must be at least :min.',
            'experience_years.required' => 'Please provide years of experience.',
            'icon.max' => 'The icon may not be greater than :max characters.',
            'id_proof.mimes' => 'The ID proof must be a JPG, JPEG, PNG, or PDF file.',
            'id_proof.max' => 'The ID proof may not be greater than :max kilobytes.',
            'id_proof.required' => 'Please upload ID proof.',
            'is_active.boolean' => 'The active status field must be true or false.',
            'is_active.required' => 'Please choose active status.',
            'is_off_day.boolean' => 'The off day status field must be true or false.',
            'is_off_day.required' => 'Please choose off day status.',
            'issue_description.max' => 'The issue description may not be greater than :max characters.',
            'issue_description.required' => 'Please describe the issue.',
            'max_price.max' => 'The maximum price may not be greater than :max.',
            'max_price.min' => 'The maximum price must be at least :min.',
            'max_price.numeric' => 'The maximum price must be a number.',
            'min_rating.max' => 'The minimum rating may not be greater than :max.',
            'min_rating.min' => 'The minimum rating must be at least :min.',
            'min_rating.numeric' => 'The minimum rating must be a number.',
            'role_id.required' => 'Please choose an account type.',
            'password.confirmed' => 'The password confirmation does not match.',
            'password.different' => 'Please choose a new password that is different from your current password.',
            'minimum_hours.required_if' => 'Please provide minimum hours for hourly pricing.',
            'response_reason.required_if' => 'Please provide a reason when cancelling the booking request.',
            'rejection_reason.required_if' => 'Please provide a reason when rejecting the booking.',
            'cancelled_reason.required_if' => 'Please provide a reason when cancelling the booking.',
            'resolution_note.required_if' => 'Please provide a resolution note for resolved or rejected disputes.',
            'minimum_hours.integer' => 'The minimum hours must be a whole number.',
            'minimum_hours.max' => 'The minimum hours may not be greater than :max.',
            'minimum_hours.min' => 'The minimum hours must be at least :min.',
            'mobile_verified.boolean' => 'The mobile verification status field must be true or false.',
            'name.max' => 'The name may not be greater than :max characters.',
            'name.required' => 'Please provide name.',
            'name.unique' => 'This service name is already in use.',
            'current_password.current_password' => 'The current password is incorrect.',
            'current_password.required' => 'Please provide your current password.',
            'password.required' => 'Please provide password.',
            'per_page.integer' => 'The items per page value must be a whole number.',
            'per_page.max' => 'The items per page value may not be greater than :max.',
            'per_page.min' => 'The items per page value must be at least :min.',
            'phone.max' => 'The phone number may not be greater than :max characters.',
            'phone.required' => 'Please provide phone number.',
            'phone.unique' => 'This phone number is already registered.',
            'price.max' => 'The price may not be greater than :max.',
            'price.min' => 'The price must be at least :min.',
            'price.numeric' => 'The price must be a number.',
            'price.required' => 'Please provide price.',
            'pricing_type.in' => 'Please choose fixed or hourly pricing.',
            'pricing_type.required' => 'Please choose a pricing type.',
            'profile_photo.image' => 'The profile photo must be an image.',
            'profile_photo.max' => 'The profile photo may not be greater than :max kilobytes.',
            'provider.max' => 'The payment provider may not be greater than :max characters.',
            'rating.integer' => 'The rating must be a whole number.',
            'rating.max' => 'The rating may not be greater than :max.',
            'rating.min' => 'The rating must be at least :min.',
            'rating.numeric' => 'The rating must be a number.',
            'rating.required' => 'Please choose a rating.',
            'reason.max' => 'The reason may not be greater than :max characters.',
            'reason.min' => 'The reason must be at least :min characters.',
            'reason.required' => 'Please provide a reason.',
            'rejection_reason.max' => 'The rejection reason may not be greater than :max characters.',
            'rejection_reason.required' => 'Please provide a rejection reason.',
            'resolution_note.max' => 'The resolution note may not be greater than :max characters.',
            'response_reason.max' => 'The response reason may not be greater than :max characters.',
            'review.max' => 'The review may not be greater than :max characters.',
            'role.in' => 'Please choose a valid role.',
            'role_id.exists' => 'Please choose a valid customer or worker account type.',
            'search.max' => 'The search term may not be greater than :max characters.',
            'service_id.exists' => 'The selected service is invalid or inactive.',
            'service_id.integer' => 'The selected service is invalid.',
            'service_id.required' => 'Please choose a service.',
            'service_id.unique' => 'This service has already been added.',
            'service_slug.max' => 'The service may not be greater than :max characters.',
            'skills.array' => 'The skills must be provided as a list.',
            'skills.max' => 'You may provide up to :max skills.',
            'skills.*.max' => 'Each skill may not be greater than :max characters.',
            'skills.*.required' => 'Please provide a skill name.',
            'slot_minutes.in' => 'Please choose a valid slot duration.',
            'slot_minutes.integer' => 'The slot duration must be a whole number.',
            'slot_minutes.max' => 'The slot duration may not be greater than :max minutes.',
            'slot_minutes.min' => 'The slot duration must be at least :min minutes.',
            'sort.in' => 'Please choose a valid sort option.',
            'start_time.date_format' => 'The start time must be in HH:MM format.',
            'start_time.required' => 'Please choose a start time.',
            'start_time.required_unless' => 'Please provide a start time unless this is marked as an off day.',
            'status.in' => 'Please choose a valid status.',
            'status.required' => 'Please choose a status.',
            'title.max' => 'The title may not be greater than :max characters.',
            'title.required' => 'Please provide title.',
            'token.required' => 'Please provide the reset token.',
            'transaction_reference.max' => 'The transaction reference may not be greater than :max characters.',
            'transaction_reference.unique' => 'This transaction reference has already been used.',
            'worker_id.exists' => 'The selected worker is invalid.',
            'worker_id.integer' => 'The selected worker is invalid.',
            'required' => 'Please provide :attribute.',
            'required_if' => 'Please provide :attribute when :other is :value.',
            'required_unless' => 'Please provide :attribute unless :other is :value.',
            'email' => 'Please enter a valid email address.',
            'unique' => 'The :attribute has already been taken.',
            'exists' => 'The selected :attribute is invalid.',
            'in' => 'The selected :attribute is invalid.',
            'integer' => 'The :attribute must be a whole number.',
            'numeric' => 'The :attribute must be a number.',
            'boolean' => 'The :attribute field must be true or false.',
            'string' => 'The :attribute must be text.',
            'array' => 'The :attribute must be a list.',
            'date_format' => 'The :attribute must match the format :format.',
            'after' => 'The :attribute must be after :date.',
            'after_or_equal' => 'The :attribute must be on or after :date.',
            'between' => 'The :attribute must be between :min and :max.',
            'image' => 'The :attribute must be an image.',
            'min' => 'The :attribute must be at least :min.',
            'max' => 'The :attribute may not be greater than :max.',
            'mimes' => 'The :attribute must be a valid file type.',
            'lowercase' => 'The :attribute must be lowercase.',
            'confirmed' => 'The :attribute confirmation does not match.',
        ];
    }

    /**
     * @return array<string, string>
     */
    public function attributes(): array
    {
        return [
            'actor_role' => 'actor role',
            'action' => 'action',
            'address' => 'service address',
            'admin_note' => 'admin note',
            'approval_status' => 'approval status',
            'available_date' => 'available date',
            'available_time' => 'available time',
            'bio' => 'bio',
            'booking_date' => 'booking date',
            'booking_id' => 'booking',
            'worker_request_id' => 'worker request',
            'cancelled_reason' => 'cancellation reason',
            'certificates' => 'certificates',
            'certificates.*' => 'certificate',
            'category' => 'category',
            'current_password' => 'current password',
            'city' => 'city',
            'commission_rate' => 'commission rate',
            'date' => 'date',
            'date_from' => 'start date',
            'date_to' => 'end date',
            'day_of_week' => 'day of week',
            'description' => 'description',
            'duration_minutes' => 'booking duration',
            'email' => 'email address',
            'end_time' => 'end time',
            'experience_years' => 'years of experience',
            'icon' => 'icon',
            'id_proof' => 'ID proof',
            'is_active' => 'active status',
            'is_off_day' => 'off day status',
            'issue_description' => 'issue description',
            'max_price' => 'maximum price',
            'min_rating' => 'minimum rating',
            'minimum_hours' => 'minimum hours',
            'mobile_verified' => 'mobile verification status',
            'name' => 'name',
            'password' => 'password',
            'per_page' => 'items per page',
            'phone' => 'phone number',
            'price' => 'price',
            'pricing_type' => 'pricing type',
            'profile_photo' => 'profile photo',
            'provider' => 'payment provider',
            'rating' => 'rating',
            'reason' => 'reason',
            'rejection_reason' => 'rejection reason',
            'resolution_note' => 'resolution note',
            'response_reason' => 'response reason',
            'review' => 'review',
            'role' => 'role',
            'role_id' => 'account type',
            'search' => 'search term',
            'service_id' => 'service',
            'service_slug' => 'service',
            'skills' => 'skills',
            'skills.*' => 'skill',
            'slot_minutes' => 'slot duration',
            'sort' => 'sort option',
            'start_time' => 'start time',
            'status' => 'status',
            'title' => 'title',
            'token' => 'token',
            'transaction_reference' => 'transaction reference',
            'worker_id' => 'worker',
        ];
    }

    protected function failedValidation(Validator $validator): void
    {
        throw new HttpResponseException(response()->json([
            'success' => false,
            'message' => $validator->errors()->first() ?: 'Validation failed',
            'errors' => $validator->errors(),
        ], 422));
    }
}
